NIBM.Procurement/Areas/Procurement/Controllers/TenderOpenController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Reporting.WebForms;
using NIBM.Procurement.Areas.Base.Controllers;
using NIBM.Procurement.Areas.Base.Models;
using NIBM.Procurement.Areas.Procurement.Models;
using NIBM.Procurement.Common;
using NIBM.Procurement;
using NIBM.Procurement.DB.Entities;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace NIBM.Procurement.Areas.Procurement.Controllers
{
    public class TenderOpenController : BaseController
    {
        private const string ProcurementTECReportFolder = "ProcurementTECReport";
        public ActionResult Index(BaseViewModel<TenderVM> vm)
        {
            vm.SetList(db.Tenders.AsQueryable(), "TenderOpenedDate");
            return View(vm);

        }

        public ActionResult CreateTender(int? id, bool tile = false)
        {
            var objTender = new TenderVM();
            var procReq = db.ProcuremenetRequests.Find(id);
            objTender.ReqByName = procReq.Employee.Title.ToString() + ". " + procReq.Employee.Initials.Trim() + " " + procReq.Employee.LastName;
            objTender.DGInitials = db.Employees.Where(x => x.DesignationID == 4 && x.Status == ActiveState.Active).Select(x => x.Title.ToEnumChar("") + ". " + x.Initials.Trim() + " " + x.LastName).FirstOrDefault();
            objTender.ApprovedOrRejectByName = procReq.DivHead.Title.ToString() + ". " + procReq.DivHead.Initials.Trim() + " " + procReq.DivHead.LastName; 
            objTender.IsTile = tile;
            objTender.ProcReqId = procReq.ProReqID;
            objTender.DGAppORRejDate = procReq.DGAppORRejDate == null ? procReq.HRAppRecommendORRejDate : procReq.DGAppORRejDate;
            objTender.CompletedDate = procReq.CompletedDate != null ? procReq.CompletedDate.Value.Date : DateTime.Today;
            objTender.TenderOpenedDate = DateTime.Now;
            objTender.TenderClosedDate = DateTime.Today.AddMonths(1);
            objTender.ReqSubject = procReq.ReqSubject;
            objTender.ReqDate = procReq.ReqDate;
            objTender.Description = procReq.Description;
            objTender.AttachmentLink = procReq.AttachmentLink;
            objTender.Comments = procReq.Comments;
            objTender.DivHeadName= procReq.DivHead.Title.ToString() + ". " + procReq.DivHead.Initials.Trim() + " " + procReq.DivHead.LastName;
            Session.SetObject(objTender);
            return View(objTender);
        }

        [HttpPost]
        public ActionResult CreateTender([Bind(Include = "TenderID,ProcReqId,TenderOpenedDate,TenderClosedDate,ReqByName,ReqDate,CompletedDate,Comments,ReqSubject,Description,DivHeadName,UserFeedback,AttachmentLink,IsTile,RowVersion")] TenderVM tender)
        {
            using (var dbTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    var obj = Session.GetObject<TenderVM>();


                    if (tender.TenderOpenedDate == null)
                    { ModelState.AddModelError("TenderOpenedDate", "Tender open date is required."); }
                    if (tender.TenderClosedDate == null)
                    { ModelState.AddModelError("TenderClosedDate", "Tender closed date is required."); }
                    if(tender.TenderClosedDate < tender.TenderOpenedDate)
                    { ModelState.AddModelError("TenderClosedDate", "Tender closed date should be greater than the tender opened date."); }
                    
                    if (obj.TenderVendors.Count == 0)
                    { ModelState.AddModelError("", "Vendors connot be empty."); }
                  

                    if (ModelState.IsValid)
                    {
                        tender.CreatedBy = this.GetCurrUser();
                        tender.CreatedDate = DateTime.Now;                      
                        var objtender = db.Tenders.Add(tender.GetEntity()).Entity;
                        db.SaveChanges();

                        var procReq = db.ProcuremenetRequests.Find(tender.ProcReqId);
                        procReq.TenderID = objtender.TenderID;
                        procReq.ModifiedBy = this.GetCurrUser();
                        procReq.ModifiedDate = DateTime.Now;

                        foreach (var det in obj.TenderVendors)
                        {
                            det.TenderID = objtender.TenderID;
                            det.CreatedBy = this.GetCurrUser();
                            det.CreatedDate = DateTime.Now;
                            objtender.TenderVendors.Add(det.GetEntity());
                        }
                        db.SaveChanges();
                        dbTransaction.Commit();
                        Session.Remove(sskCrtdObj);
                        AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Tendor opened successfully.");
                        return RedirectToAction("Details", new { id = objtender.TenderID, IsTile = tender.IsTile });
                    }
                }
                catch (DbEntityValidationException dbEx)
                {
                    this.ShowEntityErrors(dbEx);
                    dbTransaction.Rollback();
                }
                catch (Exception ex)
                {
                    AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message);
                    dbTransaction.Rollback();
                }
            }
            return View(tender);
        }

        public ActionResult Details(int? id, bool IsTile = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tenderdetails = db.Tenders.Find(id);
            if (tenderdetails == null)
            {
                return HttpNotFound();
            }

            var obj = new TenderVM(tenderdetails);
            obj.IsTile = IsTile;

            Session.SetObject(obj);
            return View(obj);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tender tenderdeails = db.Tenders.Find(id);
            if (tenderdeails == null)
            {
                return HttpNotFound();
            }
            var obj = new TenderVM(tenderdeails);
            obj.CompletedDate = obj.CompletedDate != null ? obj.CompletedDate.Value.Date : DateTime.Today;
            Session.SetObject(obj);
            return View(obj);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "TenderID,ProcReqId,TenderOpenedDate,TenderClosedDate,ReqByName,ReqDate,CompletedDate,Comments,ReqSubject,Description,DivHeadName,UserFeedback,AttachmentLink,RowVersion")] TenderVM tender)
        {
            byte[] curRowVersion = null;
            using (var dbTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    var sessionTender = Session.GetObject<TenderVM>();

                    if (tender.TenderOpenedDate == null)
                    { ModelState.AddModelError("TenderOpenedDate", "Tender open date is required."); }
                    if (tender.TenderClosedDate == null)
                    { ModelState.AddModelError("TenderClosedDate", "Tender closed date is required."); }

                    if (ModelState.IsValid)
                    {
                        curRowVersion = sessionTender.RowVersion;
                        var obj = db.Tenders.Find(tender.TenderID);

                        obj.ModifiedBy = this.GetCurrUser();
                        obj.ModifiedDate = DateTime.Now;
                        var modObj = tender.GetEntity();
                        modObj.CopyContent(obj, "TenderID,ProcReqId,TenderOpenedDate,TenderClosedDate");

                        db.TenderVendors.RemoveRange(obj.TenderVendors.Where(x =>
                           !sessionTender.TenderVendors.Select(y => y.TenderVendorID).ToList().Contains(x.TenderVendorID)));

                        foreach (var det in sessionTender.TenderVendors)
                        {
                            var objTenVen = db.TenderVendors.Find(det.TenderVendorID);
                            if (objTenVen == null)
                            {
                                det.TenderID = obj.TenderID;
                                det.CreatedBy = this.GetCurrUser();
                                det.CreatedDate = DateTime.Now;
                                obj.TenderVendors.Add(det.GetEntity());
                            }
                            else
                            {
                                var modObjDet = det.GetEntity();
                                modObjDet.CopyContent(objTenVen, "VendorID");

                                objTenVen.ModifiedBy = this.GetCurrUser();
                                objTenVen.ModifiedDate = DateTime.Now;
                            }
                        }

                        db.SaveChanges();
                        dbTransaction.Commit();

                        AddAlert(AlertStyles.success, "Tender modified successfully.");
                        return RedirectToAction("Details", new { id = tender.TenderID});
                    }
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    this.ShowConcurrencyErrors(ex);
                    tender.RowVersion = curRowVersion;
                    dbTransaction.Rollback();
                }
                catch (DbEntityValidationException dbEx)
                { this.ShowEntityErrors(dbEx); dbTransaction.Rollback(); }
                catch (Exception ex)

NIBM.Procurement/Areas/Procurement/Views/TenderOpen/BoardApprove.cshtml
@model NIBM.Procurement.Areas.Procurement.Models.TenderVM
@{
    ViewBag.Title = "Spec and TEC Report";
}


<div class="form-horizontal">
    <div class="form-group row">
        <br />
        @using (Html.BeginForm("BoardApprove", "TenderOpen"))
        {
            @Html.HiddenFor(model => model.RowVersion)
            @Html.HiddenFor(model => model.TenderID)
            @Html.HiddenFor(model => model.IsTile)

            <br />
            <div class="card text-dark bg-light mb-3">
                <div class="card-header">
                    <p>
                        <div class="d-grid gap-2 d-md-block">
                            <input type="submit" value="Board Approve" class="btn btn-success" style="min-width:75px" />

                            @Html.ConfirmSubmitButton("Board Reject", "Are you sure you want to reject ?", "Confirm Board Reject", "<span class='bi bi-x-circle'></span> Board Reject", new { @class = "btn btn-danger", style = "min-width:75px" }, "btn-danger", "BoardReject")
                            <span style="font-weight:bold; font-size:14px; margin-right:8%;" class="bi bi-circle-fill float-right
                            @(Model.TenderStatus == TenderStatus.TenderOpen ? "orange-status" : Model.TenderStatus == TenderStatus.TECSelected ? "light-blue-status" :
                                Model.TenderStatus == TenderStatus.TECRecommend ? "blue-status" : "green-status")">
                                &nbsp; @Model.TenderStatus.ToEnumChar()
                            </span>
                        </div>
                    </p>
                </div>
                <div class="card-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group row">
                            @Html.LabelFor(model => model.SelectedVendorId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.PopUpSelectorFor(model => model.SelectedVendorId, "Base", "Data", "GetVendors", new { @class = "form-select form-select-sm form-control form-control-sm rounded-pill" }, "Please select a Vendor", dspFormat: "{1}", hiddenIndices: "0", dataParas: new { tenderID = Model.TenderID })
                                @Html.ValidationMessageFor(model => model.SelectedVendorId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.TenderOpenedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.TenderOpenedDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                            @Html.LabelFor(model => model.TenderClosedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.TenderClosedDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="control-label col-md-2">Specification Attachment</label>
                            <div class="col-md-4">
                                <a href=@Model.RecommenedSpecification class="btn btn-primary" target="_blank"><span class='bi bi-search'></span> View</a>
                            </div>
                            <label class="control-label col-md-2">TEC Report</label>
                            <div class="col-md-4">
                                <a href=@Model.TECReportAttachment class="btn btn-primary" target="_blank"><span class='bi bi-search'></span> View</a>
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.ReqByName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ReqByName, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                            @Html.LabelFor(model => model.ReqDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ReqDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.CompletedDate, "Completed Date", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.CompletedDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.ReqSubject, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ReqSubject, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>
                        <br />
                        <div class="form-group row">
                            @if (!Model.AttachmentLink.IsBlank())
                            {
                                var Attachment = "Request Attachment";
                                @Html.LabelFor(model => Attachment, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-4">
                                    <a href=@Model.AttachmentLink class="btn btn-primary" target="_blank"><span class='bi bi-download'></span></a>
                                </div>
                            }
                            @Html.LabelFor(model => model.DivHeadName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.DivHeadName, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>
                        <div class="form-group row">
                            @if (Model.UserFeedback != null)
                            {
                                @Html.LabelFor(model => model.UserFeedback, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-4">
                                    @Html.EditorFor(model => model.UserFeedback, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
</div>
<div class="card shadow mb-3">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Vendors</h6>
    </div>
    <div class="card-body px-5 pb-5">
        <div class="ChildContent">
            @{ Html.RenderAction("ChildIndex", new { id = Model.TenderID, isToEdit = false }); }
        </div>
    </div>
</div>
<div class="card shadow">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">TEC Members</h6>
    </div>
    <div class="card-body px-5 pb-5">
        <div class="ChildContent">
            @{ Html.RenderAction("ChildtecIndex", new { id = Model.TenderID, isToEdit = false }); }
        </div>
    </div>
</div>
<br />
<div>
    <br /><br />@Html.ActionLink("Back to Index", "ProcurementProcessIndex", "ProcurementProcess", new { area = "Procurement", numericVar1 = 3 }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/tender/tender")


}

NIBM.Procurement/Areas/Procurement/Views/TenderOpen/CreateTender.cshtml
@model NIBM.Procurement.Areas.Procurement.Models.TenderVM
@{
    ViewBag.Title = "Tender Open";
}


<div class="form-horizontal">
    <div class="form-group row">
        <br />
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.TenderID)
            @Html.HiddenFor(model => model.RowVersion)
            @Html.HiddenFor(model => model.ProcReqId)
            @Html.HiddenFor(model => model.IsTile)


            <div class="card text-dark bg-light mb-3">
                <div class="card-header">
                    <div class="d-grid gap-2 d-md-block">
                        <input type="submit" value="Open Tender" class="btn btn-primary" style="min-width:75px" />
                        <span style="font-weight:bold; text-align:center;" class="float-right col-md-4"> ( DG Approved on @(Model.DGAppORRejDate.ToDateString("yyyy-MM-dd")))</span> <br />
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group row">
                            @Html.LabelFor(model => model.TenderOpenedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.TenderOpenedDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", type = "JQ-date" } })
                            </div>
                            @Html.LabelFor(model => model.TenderClosedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.TenderClosedDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", type = "JQ-date" } })
                        </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.ReqByName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ReqByName, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                            @Html.LabelFor(model => model.ReqDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ReqDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.CompletedDate, "Completed Date", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.CompletedDate, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.CompletedDate, "", new { @class = "text-danger" })

                            </div>
                            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.ReqSubject, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ReqSubject, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>
                        <br />
                        <div class="form-group row">
                            @if (!Model.AttachmentLink.IsBlank())
                            {
                                var Attachment = "Request Attachment";
                                @Html.LabelFor(model => Attachment, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-4">
                                    <a href=@Model.AttachmentLink class="btn btn-primary" target="_blank"><span class='bi bi-download'></span></a>
                                </div>
                            }
                            @Html.LabelFor(model => model.DivHeadName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.DivHeadName, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                            </div>
                        </div>
                        <div class="form-group row">
                            @if (Model.UserFeedback != null)
                            {
                                @Html.LabelFor(model => model.UserFeedback, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-4">
                                    @Html.EditorFor(model => model.UserFeedback, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill", @readonly = "readonly" } })
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="card shadow">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Vendors</h6>
    </div>
    <div class="card-body px-5 pb-5">
        <div class="ChildContent">
            @{ Html.RenderAction("ChildIndex", new { id = Model.TenderID, isToEdit = true }); }
        </div>
    </div>
</div>
<br />
<div>
    @if (Model.IsTile == true)
    {
        <br /><br />
        @Html.ActionLink("Back to Index", "ProcurementProcessIndex", "ProcurementProcess", new { area = "Procurement", numericVar1 = 3 }, null)
    }
    else
    {
        <br /><br />
        @Html.ActionLink("Back to Index", "Index", "TenderOpen", new { area = "Procurement" }, null)
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/tender/tender")
}

NIBM.Procurement/Areas/Procurement/Views/TenderOpen/Index.cshtml
@model NIBM.Procurement.Common.BaseViewModel<NIBM.Procurement.Areas.Procurement.Models.TenderVM>

@{
    ViewBag.Title = "Tenders";
    var grid = Model.GetGrid();
}
@{
    var srchOpts = new List<SelectListItem>();
    srchOpts.Add(new SelectListItem { Text = "Tender Opened Date", Value = "TenderOpenedDate" });
    srchOpts.Add(new SelectListItem { Text = "Tender Closed Date", Value = "TenderClosedDate" });
    srchOpts.Add(new SelectListItem { Text = "Requested By", Value = "ReqByName" });
    srchOpts.Add(new SelectListItem { Text = "Description", Value = "Description" });

}
<div class="card shadow mt-1">
    <div class="card-header py-3">
    </div>
    <div class="card-body pb-5">
        @using (Html.BeginForm("Index", "TenderOpen", FormMethod.Get))
        {
            <div class="form-horizontal row justify-content-center mt-3">
                <div class="col-md-4">
                    <div class="form-group row">
                        @Html.Label("Search By", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("FilterBy", new SelectList(srchOpts, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group row">
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Filter, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                        </div>
                    </div>
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Search" name="Search" class="btn btn-outline-secondary" />
                </div>
            </div>

            <div class="table-responsive mt-5" id="content">
                @grid.GetHtml(
                tableStyle: "table table-hover no-foot",
                mode: WebGridPagerModes.All,
                columns: grid.Columns(
                grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-search' style='color:white'></span>", "View Details", "Details", routeValues: new { id = item.TenderID, IsTile = false }, htmlAttributes: new { @class = "btn btn-primary btn-sm" }), style: "btn-1"),
                grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-pencil-square' style='color:black'></span>", "Proceed to Edit", "Edit", routeValues: new { id = item.TenderID }, htmlAttributes: new { @class = "btn btn-warning btn-sm" }), style: "btn-1"),
                grid.SortColumn(columnName: "TenderOpenedDate", header: "Tender Opened Date", format: (item) => item.TenderOpenedDate.ToString("yyyy-MM-dd")),
                grid.SortColumn(columnName: "TenderClosedDate", header: "Tender Close Date", format: (item) => item.TenderClosedDate.ToString("yyyy-MM-dd")),
                grid.SortColumn(columnName: "ReqByName", header: "Requested By"),
                grid.SortColumn(columnName: "ReqSubject", header: "Subject"),
                grid.SortColumn(columnName: "Description", header: " Description"),
                grid.SortColumn(columnName: "ReqDate", header: "Requested Date", format: (item) => item.ReqDate.ToString("yyyy-MM-dd")),
                grid.SortColumn(columnName: "DivHeadName", header: "Immediate Supervisor")
                ))

                <div id="content-footer">
                    @grid.PagerList(WebGridPagerModes.All, Model.PageSize, Model.TotalRecords)
                </div>
            </div>
        }
    </div>
</div>