NIBM.Procurement/Areas/Admin/Controllers/DepartmentsController.cs
using Microsoft.EntityFrameworkCore;
using NIBM.Procurement.Areas.Admin.Models;
using NIBM.Procurement.Areas.Base.Controllers;
using NIBM.Procurement.Common;
using NIBM.Procurement.DB.Entities;
using System;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NIBM.Procurement.Areas.Admin.Controllers
{
    public class DepartmentsController : BaseController
    {
        public ActionResult Index(BaseViewModel<DepartmentVM> vm)
        {
            vm.SetList(db.Departments.AsQueryable(), "Description");
            return View(vm);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(new DepartmentVM(department));
        }

        public ActionResult Create()
        {
            var department = new DepartmentVM() { Status = ActiveState.Active };
            return View(department);
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "DepartmentID,Description,IsAcademic,Status")] DepartmentVM department)
        {
            try
            {
                var existingDepartment = db.Departments.Where(e => e.Description == department.Description).FirstOrDefault();

                if (existingDepartment != null)
                { ModelState.AddModelError("Description", "Department Name Already Exist"); }

                if (ModelState.IsValid)
                {
                    department.CreatedBy = this.GetCurrUser();
                    department.CreatedDate = DateTime.Now;
                    db.Departments.Add(department.GetEntity());
                    db.SaveChanges();

                    AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Department created successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message); }

            return View(department);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(new DepartmentVM(department));
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "DepartmentID,Description,IsAcademic,Status,RowVersion")] DepartmentVM department)
        {
            byte[] curRowVersion = null;
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = db.Departments.Find(department.DepartmentID);
                    if (obj == null)
                    { throw new DbUpdateConcurrencyException(); }

                    curRowVersion = obj.RowVersion;
                    var modObj = department.GetEntity();
                    modObj.CopyContent(obj, "Description,IsAcademic,Status");

                    obj.ModifiedBy = this.GetCurrUser();
                    obj.ModifiedDate = DateTime.Now;

                    db.Entry(obj).OriginalValues["RowVersion"] = department.RowVersion;
                    db.SaveChanges();

                    AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Department modified successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex);
                department.RowVersion = curRowVersion;
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message); }

            return View(department);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(DepartmentVM department)
        {
            try
            {
                var obj = db.Departments.Find(department.DepartmentID);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }
                db.Detach(obj);

                db.Entry(department.GetEntity()).State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Department deleted successfully.");
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex, true);
                if (ex.Message == "")
                { return RedirectToAction("Index"); }
            }
            catch (Exception ex)
            {
                AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message);
            }
            return RedirectToAction("Details", new { id = department.DepartmentID });
        }
    }
}

NIBM.Procurement/Areas/Admin/Views/Departments/Create.cshtml
@model NIBM.Procurement.Areas.Admin.Models.DepartmentVM

@{
    ViewBag.Title = "Create Department";
}

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <br />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>

        <div class="form-group row">
            @Html.LabelFor(model => model.IsAcademic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.IsAcademic, new { htmlAttributes = new { @class = "form-checkbox" } })
                @Html.ValidationMessageFor(model => model.IsAcademic, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumEditorFor(model => model.Status, htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
}

<div>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NIBM.Procurement/Areas/Admin/Views/Departments/Details.cshtml
@model NIBM.Procurement.Areas.Admin.Models.DepartmentVM

@{
    ViewBag.Title = "Department Details";
}

<div>
    <br />
    @using (Html.BeginForm("Delete", "Departments"))
    {
        @Html.HiddenFor(model => model.DepartmentID)
        @Html.HiddenFor(model => model.RowVersion)

        <p>
            <div class="d-grid gap-2 d-md-block">
                @Html.ActionLink("Edit", "Edit", new { id = Model.DepartmentID }, new { @class = "btn btn-primary", style = "min-width:75px" })
                @Html.ConfirmSubmitButton("Delete", "Are you sure you want to delete?", "Confirm department deletion",
                 "<span class='bi bi-trash'></span> Delete", new { @class = "btn btn-danger", style = "min-width:75px" })
            </div>
        </p>
    }

        <div class="form-horizontal">
            <div class="form-group row">
                @Html.LabelFor(model => model.IsAcademic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DetailsViewFor(model => model.IsAcademic)
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DetailsViewFor(model => model.Description)
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DetailsViewFor(model => model.Status)
                </div>
            </div>

        </div>
</div>
<p>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</p>

NIBM.Procurement/Areas/Admin/Views/Departments/Edit.cshtml
@model NIBM.Procurement.Areas.Admin.Models.DepartmentVM

@{
    ViewBag.Title = "Edit Department";
}

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <br />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentID)
        @Html.HiddenFor(model => model.RowVersion)


        <div class="form-group row">
            @Html.LabelFor(model => model.IsAcademic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.IsAcademic, new { htmlAttributes = new { @class = "form-checkbox" } })
                @Html.ValidationMessageFor(model => model.IsAcademic, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumEditorFor(model => model.Status, htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div>
    <br /><br />@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NIBM.Procurement/Areas/Admin/Views/Departments/Index.cshtml
@model NIBM.Procurement.Common.BaseViewModel<NIBM.Procurement.Areas.Admin.Models.DepartmentVM>

@{
    ViewBag.Title = "Departments";
    var grid = Model.GetGrid();
}

@{
    var srchOpts = new List<SelectListItem>();
    srchOpts.Add(new SelectListItem { Text = "Description", Value = "Description" });
}

<p>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary", style = "min-width:75px" })
</p>

@using (Html.BeginForm("Index", null, FormMethod.Get))
{
    <div class="form-horizontal row">
        <div class="col-md-4">
            <div class="form-group row">
                @Html.Label("Search By", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownList("FilterBy", new SelectList(srchOpts, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Filter, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <input type="submit" value="Search" name="Search" class="btn btn-outline-secondary" />
        </div>
    </div>
    <br />

    <div id="content">
        @grid.GetHtml(
        tableStyle: "table table-hover no-foot",
        mode: WebGridPagerModes.All,
        columns: grid.Columns(
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-search' style='color:white'></span>", "View Details", "Details", routeValues: new { id = item.DepartmentID }, htmlAttributes: new { @class = "btn btn-primary btn-sm" }), style: "btn-1"),
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-pencil-square' style='color:black'></span>", "Proceed to Edit", "Edit", routeValues: new { id = item.DepartmentID }, htmlAttributes: new { @class = "btn btn-warning btn-sm" }), style: "btn-1"),
            grid.SortColumn(columnName: "Description", header: "Description"),
            grid.SortColumn(columnName: "IsAcademic", header: "Is Academic", format: (item) => item.IsAcademic ? "Yes" : "-"),
            grid.SortColumn(columnName: "Status", header: "Status", format: (item) => ((Enum)item.Status).ToEnumChar())
            ))

        <div id="content-footer">
            @grid.PagerList(WebGridPagerModes.All, Model.PageSize, Model.TotalRecords)
        </div>
    </div>
}