NIBM.Procurement/Areas/Admin/Controllers/BranchesController.cs
using Microsoft.EntityFrameworkCore;
using NIBM.Procurement.Areas.Admin.Models;
using NIBM.Procurement.Areas.Base.Controllers;
using NIBM.Procurement.Common;
using NIBM.Procurement;
using NIBM.Procurement.DB.Entities;
using System;
using System.Net;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;

namespace NIBM.Procurement.Areas.Admin.Controllers
{
    public class BranchesController : BaseController
    {
        public ActionResult Index(BaseViewModel<BranchVM> vm)
        {
            vm.SetList(db.Branches.AsQueryable(), "Description");
            return View(vm);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(new BranchVM(branch));
        }

        public ActionResult Create()
        {
            var branch = new BranchVM() { Status = ActiveState.Active };
            return View(branch);
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "BranchID,Description,Address,TelNo_1,TelNo_2,FaxNo_1,FaxNo_2,Status")] BranchVM branch)
        {
            using (var dbTransaction = db.Database.BeginTransaction())
            {
                try
                {

                    var existingBranch = db.Branches.Where(e=>e.Description==branch.Description).FirstOrDefault();
                    if (existingBranch != null)
                    { ModelState.AddModelError("Description", "Branch Already Exist"); }

                    if (ModelState.IsValid)
                    {
                        branch.CreatedBy = this.GetCurrUser();
                        branch.CreatedDate = DateTime.Now;
                        db.Branches.Add(branch.GetEntity());
                        db.SaveChanges();

                        AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Branch created successfully.");
                        return RedirectToAction("Index");
                    }
                }
                catch (DbEntityValidationException dbEx)
                { this.ShowEntityErrors(dbEx); }
                catch (Exception ex)
                { AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message); }
            }
            return View(branch);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(new BranchVM(branch));
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "BranchID,Description,Address,TelNo_1,TelNo_2,FaxNo_1,FaxNo_2,Status,RowVersion")] BranchVM branch)
        {
            byte[] curRowVersion = null;
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = db.Branches.Find(branch.BranchID);
                    if (obj == null)
                    { throw new DbUpdateConcurrencyException(); }

                    curRowVersion = obj.RowVersion;
                    var modObj = branch.GetEntity();
                    modObj.CopyContent(obj, "Description,Address,TelNo_1,TelNo_2,FaxNo_1,FaxNo_2,Status");

                    obj.ModifiedBy = this.GetCurrUser();
                    obj.ModifiedDate = DateTime.Now;

                    db.Entry(obj).OriginalValues["RowVersion"] = branch.RowVersion;
                    db.SaveChanges();

                    AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Branch modified successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex);
                branch.RowVersion = curRowVersion;
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message); }

            return View(branch);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(BranchVM branch)
        {
            try
            {
                var obj = db.Branches.Find(branch.BranchID);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }
                db.Detach(obj);

                db.Entry(branch.GetEntity()).State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Branch deleted successfully.");
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex, true);
                if (ex.Message == "")
                { return RedirectToAction("Index"); }
            }
            catch (Exception ex)
            {
                AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message);
            }
            return RedirectToAction("Details", new { id = branch.BranchID });
        }
    }
}

NIBM.Procurement/Areas/Admin/Views/Branches/Create.cshtml
@model NIBM.Procurement.Areas.Admin.Models.BranchVM

@{
    ViewBag.Title = "Create Branch";
}

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <br />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumEditorFor(model => model.Status, htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
}

<div>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NIBM.Procurement/Areas/Admin/Views/Branches/Details.cshtml
@model NIBM.Procurement.Areas.Admin.Models.BranchVM

@{
    ViewBag.Title = "Branch Details";
}

<div>
    <br />
    @using (Html.BeginForm("Delete", "Branches"))
    {
        @Html.HiddenFor(model => model.BranchID)
        @Html.HiddenFor(model => model.RowVersion)

        <p>
            <div class="d-grid gap-2 d-md-block">
                @Html.ActionLink("Edit", "Edit", new { id = Model.BranchID }, new { @class = "btn btn-primary", style = "min-width:75px" })
                @Html.ConfirmSubmitButton("Delete", "Are you sure you want to delete?", "Confirm branch deletion",
                 "<span class='bi bi-trash'></span> Delete", new { @class = "btn btn-danger", style = "min-width:75px" })
            </div>
        </p>
    }

    <div class="form-horizontal">
        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.Description)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.Address)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.TelNo_1)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.TelNo_2)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.FaxNo_1)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.FaxNo_2)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.Status)
            </div>
        </div>

    </div>
</div>
<p>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</p>

NIBM.Procurement/Areas/Admin/Views/Branches/Edit.cshtml
@model NIBM.Procurement.Areas.Admin.Models.BranchVM

@{
    ViewBag.Title = "Edit Branch";
}

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <br />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BranchID)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumEditorFor(model => model.Status, htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NIBM.Procurement/Areas/Admin/Views/Branches/Index.cshtml
@model NIBM.Procurement.Common.BaseViewModel<NIBM.Procurement.Areas.Admin.Models.BranchVM>

@{
    ViewBag.Title = "Branches";
    var grid = Model.GetGrid();
}

@{
    var srchOpts = new List<SelectListItem>();
    srchOpts.Add(new SelectListItem { Text = "Description", Value = "Description" });
}

<p>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary", style = "min-width:75px" })
</p>

@using (Html.BeginForm("Index", null, FormMethod.Get))
{
    <div class="form-horizontal row">
        <div class="col-md-4">
            <div class="form-group row">
                @Html.Label("Search By", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownList("FilterBy", new SelectList(srchOpts, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Filter, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <input type="submit" value="Search" name="Search" class="btn btn-outline-secondary" />
        </div>
    </div>
    <br />

    <div id="content">
        @grid.GetHtml(
        tableStyle: "table table-hover no-foot",
        mode: WebGridPagerModes.All,
        columns: grid.Columns(
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-search' style='color:white'></span>", "View Details", "Details", routeValues: new { id = item.BranchID }, htmlAttributes: new { @class = "btn btn-primary btn-sm" }), style: "btn-1"),
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-pencil-square' style='color:black'></span>", "Proceed to Edit", "Edit", routeValues: new { id = item.BranchID }, htmlAttributes: new { @class = "btn btn-warning btn-sm" }), style: "btn-1"),
            grid.SortColumn(columnName: "Description", header: "Description"),
            grid.SortColumn(columnName: "Address", header: "Address"),
            grid.SortColumn(columnName: "TelNo_1", header: "Telephone 1"),
            grid.SortColumn(columnName: "TelNo_2", header: "Telephone 2"),
            grid.SortColumn(columnName: "FaxNo_1", header: "Fax 1"),
            grid.SortColumn(columnName: "FaxNo_2", header: "Fax 2"),
            grid.SortColumn(columnName: "Status", header: "Status", format: (item) => ((Enum)item.Status).ToEnumChar())
            ))

        <div id="content-footer">
            @grid.PagerList(WebGridPagerModes.All, Model.PageSize, Model.TotalRecords)
        </div>
    </div>
}