NIBM.Procurement/Areas/Admin/Controllers/BranchDepartmentsController.cs
using Microsoft.EntityFrameworkCore;
using NIBM.Procurement.Areas.Admin.Models;
using NIBM.Procurement.Areas.Base.Controllers;
using NIBM.Procurement.Common;
using NIBM.Procurement.DB.Entities;
using System;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NIBM.Procurement.Areas.Admin.Controllers
{
    public class BranchDepartmentsController : BaseController
    {
        public ActionResult Index(BaseViewModel<BranchDepartmentVM> vm)
        {
            vm.SetList(db.BranchDepartments.AsQueryable(), "BranchDesc");
            return View(vm);
        }

        public ActionResult Details(int? branchId, int? departmentId)
        {
            if (branchId == null || departmentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BranchDepartment branchDepartment = db.BranchDepartments.Find(branchId, departmentId);
            if (branchDepartment == null)
            {
                return HttpNotFound();
            }
            return View(new BranchDepartmentVM(branchDepartment));
        }

        public ActionResult Create()
        {
            var branchDepartment = new BranchDepartmentVM() { Status = ActiveState.Active };
            return View(branchDepartment);
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "BranchID,DepartmentID,TelNo_1,TelNo_2,FaxNo_1,FaxNo_2,Status")] BranchDepartmentVM branchDepartment)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    branchDepartment.CreatedBy = this.GetCurrUser();
                    branchDepartment.CreatedDate = DateTime.Now;
                    db.BranchDepartments.Add(branchDepartment.GetEntity());
                    db.SaveChanges();

                    AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Branch Department created successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message); }

            return View(branchDepartment);
        }

        public ActionResult Edit(int? branchId, int? departmentId)
        {
            if (branchId == null || departmentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BranchDepartment branchDepartment = db.BranchDepartments.Find(branchId, departmentId);
            if (branchDepartment == null)
            {
                return HttpNotFound();
            }
            return View(new BranchDepartmentVM(branchDepartment));
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "BranchID,DepartmentID,TelNo_1,TelNo_2,FaxNo_1,FaxNo_2,Status,RowVersion")] BranchDepartmentVM branchDepartment)
        {
            byte[] curRowVersion = null;
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = db.BranchDepartments.Find(branchDepartment.BranchID, branchDepartment.DepartmentID);
                    if (obj == null)
                    { throw new DbUpdateConcurrencyException(); }

                    curRowVersion = obj.RowVersion;
                    var modObj = branchDepartment.GetEntity();
                    modObj.CopyContent(obj, "TelNo_1,TelNo_2,FaxNo_1,FaxNo_2,Status");

                    obj.ModifiedBy = this.GetCurrUser();
                    obj.ModifiedDate = DateTime.Now;

                    db.Entry(obj).OriginalValues["RowVersion"] = branchDepartment.RowVersion;
                    db.SaveChanges();

                    AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Branch Department modified successfully.");
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex);
                branchDepartment.RowVersion = curRowVersion;
            }
            catch (DbEntityValidationException dbEx)
            { this.ShowEntityErrors(dbEx); }
            catch (Exception ex)
            { AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message); }

            return View(branchDepartment);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(BranchDepartmentVM branchDepartment)
        {
            try
            {
                var obj = db.BranchDepartments.Find(branchDepartment.BranchID, branchDepartment.DepartmentID);
                if (obj == null)
                { throw new DbUpdateConcurrencyException(""); }
                db.Detach(obj);

                db.Entry(branchDepartment.GetEntity()).State = EntityState.Deleted;
                db.SaveChanges();

                AddAlert(NIBM.Procurement.Common.AlertStyles.success, "Branch Department deleted successfully.");
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                this.ShowConcurrencyErrors(ex, true);
                if (ex.Message == "")
                { return RedirectToAction("Index"); }
            }
            catch (Exception ex)
            {
                AddAlert(NIBM.Procurement.Common.AlertStyles.danger, ex.GetInnerException().Message);
            }
            return RedirectToAction("Details", new { branchID = branchDepartment.BranchID, departmentID = branchDepartment.DepartmentID });
        }
    }
}

NIBM.Procurement/Areas/Admin/Views/BranchDepartments/Create.cshtml
@model NIBM.Procurement.Areas.Admin.Models.BranchDepartmentVM

@{
    ViewBag.Title = "Create Branch Department";
}

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <br />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.BranchID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PopUpSelectorFor(model => model.BranchID, "Base", "Data", "GetBranches", new { @class = "form-select form-select-sm form-control form-control-sm rounded-pill" }, "Please select a Branch", dspFormat: "{1}", hiddenIndices: "0")
                @Html.ValidationMessageFor(model => model.BranchID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PopUpSelectorFor(model => model.DepartmentID, "Base", "Data", "GetDepartments", new { @class = "form-select form-select-sm form-control form-control-sm rounded-pill" }, "Please select a Department", dspFormat: "{1}", popUpWidth: 400, hiddenIndices: "0")
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumEditorFor(model => model.Status, htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NIBM.Procurement/Areas/Admin/Views/BranchDepartments/Details.cshtml
@model NIBM.Procurement.Areas.Admin.Models.BranchDepartmentVM

@{
    ViewBag.Title = "Branch Department Details";
}

<div>
    <br />
    @using (Html.BeginForm("Delete", "BranchDepartments"))
    {
        @Html.HiddenFor(model => model.BranchID)
        @Html.HiddenFor(model => model.DepartmentID)
        @Html.HiddenFor(model => model.RowVersion)

        <p>
            <div class="d-grid gap-2 d-md-block">
                @Html.ActionLink("Edit", "Edit", new { branchID = Model.BranchID, departmentID = Model.DepartmentID }, new { @class = "btn btn-primary", style = "min-width:75px" })
                @Html.ConfirmSubmitButton("Delete", "Are you sure you want to delete?", "Confirm branch department deletion",
                 "<span class='bi bi-trash'></span> Delete", new { @class = "btn btn-danger", style = "min-width:75px" })
            </div>
        </p>
    }

    <div class="form-horizontal">
        <div class="form-group row">
            @Html.LabelFor(model => model.BranchID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.BranchDesc)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.DepartmentDesc)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.TelNo_1)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.TelNo_2)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.FaxNo_1)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.FaxNo_2)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DetailsViewFor(model => model.Status)
            </div>
        </div>
    </div>
</div>
<p>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</p>

NIBM.Procurement/Areas/Admin/Views/BranchDepartments/Edit.cshtml
@model NIBM.Procurement.Areas.Admin.Models.BranchDepartmentVM

@{
    ViewBag.Title = "Edit Branch Department";
}

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <br />
        <p>
            <input type="submit" value="Save" class="btn btn-primary" style="min-width:75px" />
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BranchID)
        @Html.HiddenFor(model => model.DepartmentID)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-group row">
            @Html.LabelFor(model => model.BranchID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PopUpSelectorFor(model => model.BranchID, "Base", "Data", "GetBranches", new { @class = "form-select form-select-sm form-control form-control-sm rounded-pill" }, "Please select a Branch", dspFormat: "{1}", hiddenIndices: "0")
                @Html.ValidationMessageFor(model => model.BranchID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PopUpSelectorFor(model => model.DepartmentID, "Base", "Data", "GetDepartments", new { @class = "form-select form-select-sm form-control form-control-sm rounded-pill" }, "Please select a Department", dspFormat: "{1}", popUpWidth: 400, hiddenIndices: "0")
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TelNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.TelNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_1, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FaxNo_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaxNo_2, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                @Html.ValidationMessageFor(model => model.FaxNo_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumEditorFor(model => model.Status, htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div>
    <br/><br/>@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NIBM.Procurement/Areas/Admin/Views/BranchDepartments/Index.cshtml
@model NIBM.Procurement.Common.BaseViewModel<NIBM.Procurement.Areas.Admin.Models.BranchDepartmentVM>

@{
    ViewBag.Title = "Branch Departments";
    var grid = Model.GetGrid();
}

@{
    var srchOpts = new List<SelectListItem>();
    srchOpts.Add(new SelectListItem { Text = "Branch", Value = "BranchDesc" });
    srchOpts.Add(new SelectListItem { Text = "Department", Value = "DepartmentDesc" });
}

<p>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary", style = "min-width:75px" })
</p>

@using (Html.BeginForm("Index", null, FormMethod.Get))
{
    <div class="form-horizontal row">
        <div class="col-md-4">
            <div class="form-group row">
                @Html.Label("Search By", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownList("FilterBy", new SelectList(srchOpts, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm rounded-pill form-select-sm" })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Filter, new { htmlAttributes = new { @class = "form-control form-control-sm rounded-pill" } })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <input type="submit" value="Search" name="Search" class="btn btn-outline-secondary" />
        </div>
    </div>
    <br />

    <div id="content">
        @grid.GetHtml(
        tableStyle: "table table-hover no-foot",
        mode: WebGridPagerModes.All,
        columns: grid.Columns(
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-search' style='color:white'></span>", "View Details", "Details", routeValues: new { branchID = item.BranchID, departmentID = item.DepartmentID }, htmlAttributes: new { @class = "btn btn-primary btn-sm" }), style: "btn-1"),
            grid.Column(null, null, format: (item) => Html.NoEncodeActionLink("<span class='bi bi-pencil-square' style='color:black'></span>", "Proceed to Edit", "Edit", routeValues: new { branchID = item.BranchID, departmentID = item.DepartmentID }, htmlAttributes: new { @class = "btn btn-warning btn-sm" }), style: "btn-1"),
            grid.SortColumn(columnName: "BranchDesc", header: "Branch"),
            grid.SortColumn(columnName: "DepartmentDesc", header: "Department"),
            grid.SortColumn(columnName: "Status", header: "Status", format: (item) =>((Enum)item.Status).ToEnumChar())
            ))

        <div id="content-footer">
            @grid.PagerList(WebGridPagerModes.All, Model.PageSize, Model.TotalRecords)
        </div>
    </div>
}